unit Testudmmovimentacao;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  Vcl.forms, TestFramework, FireDAC.Stan.Option, FireDAC.Stan.Async, udmmovimentacao,
  FireDAC.Stan.Error, Data.DB, FireDAC.Phys.Intf, System.SysUtils, FireDAC.DApt,
  FireDAC.Stan.Intf, Movimentacao, FireDAC.Comp.Client, FireDAC.Stan.Param,
  FireDAC.Comp.DataSet, FireDAC.DApt.Intf, FireDAC.DatS, System.Classes;

type
  // Test methods for class TdmMovimentacao

  TestTdmMovimentacao = class(TTestCase)
  strict private
    FdmMovimentacao: TdmMovimentacao;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInsert;
  end;

implementation

procedure TestTdmMovimentacao.SetUp;
begin
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TdmMovimentacao, dmmovimentacao);

end;

procedure TestTdmMovimentacao.TearDown;
begin
  FdmMovimentacao.Free;
  FdmMovimentacao := nil;
end;

procedure TestTdmMovimentacao.TestInsert;
var
  ReturnValue: Boolean;
  sErro: string;
  iId: Integer;
  oMovimento: TMovimento;
begin
  // TODO: Setup method call parameters
  ReturnValue := FdmMovimentacao.Insert(oMovimento, iId, sErro);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTdmMovimentacao.Suite);
end.

